language: node_js
node_js:
  - 8
  - 10
branches:
  only:
    - master
    - stable
before_install: 
  - "npm install -g add nyc"
script:
  - "npm run test-ci"
after_script:
  - "npm install -g coveralls codeclimate-test-reporter"
  - "dir ./coverage/"
  - "cat ./coverage/lcov.info | coveralls"
  - "cat ./coverage/lcov.info | CODECLIMATE_REPO_TOKEN=3435a4d60c44136e262d797bc7292611dc4c87a632645e2469510b9b066ec94a codeclimate-test-reporter"
addons:
  code_climate:
    repo_token: 3435a4d60c44136e262d797bc7292611dc4c87a632645e2469510b9b066ec94a