environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "11"
branches:
  only:
    - master
    - stable
install:
  - "yarn global add nyc eslint"
  - "yarn"
build: 
test_script:
  - "yarn test-ci"
version: "{build}"